import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Toaster } from "react-hot-toast"; // ✅ Import the Toaster

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster position="top-center" reverseOrder={false} /> {/* ✅ Must be inside body */}
      </body>
    </html>
  );
}
